
export interface Product {
  asin: string
  name: string
  price: number
  rating: number
  review_count: number
  affiliate_url: string
  image_url: string
  pin_image_url: string | null
  primary_image_url: string
  has_pin: boolean
  category: string
}

const ALL_PRODUCTS: Product[] = [
  {
    "asin": "B07Z9Y4C3C",
    "name": "La Roche-Posay Pure Retinol Face Serum",
    "price": 44.99,
    "rating": 4.6,
    "review_count": 12000,
    "affiliate_url": "https://www.amazon.com/dp/B07Z9Y4C3C?tag=mintbrooks-20",
    "image_url": "/api/pin-image/B07Z9Y4C3C",
    "primary_image_url": "/api/pin-image/B07Z9Y4C3C",
    "pin_image_url": null,
    "has_pin": false,
    "category": "beauty"
  },
  {
    "asin": "B07PM79MSC",
    "name": "La Roche-Posay Pure 12% Vitamin C Serum",
    "price": 44.99,
    "rating": 4.4,
    "review_count": 8500,
    "affiliate_url": "https://www.amazon.com/dp/B07PM79MSC?tag=mintbrooks-20",
    "image_url": "/api/pin-image/B07PM79MSC",
    "primary_image_url": "/api/pin-image/B07PM79MSC",
    "pin_image_url": null,
    "has_pin": false,
    "category": "beauty"
  },
  {
    "asin": "B083N1H6P7",
    "name": "Paula's Choice CLINICAL 20% Niacinamide",
    "price": 55.0,
    "rating": 4.5,
    "review_count": 6200,
    "affiliate_url": "https://www.amazon.com/dp/B083N1H6P7?tag=mintbrooks-20",
    "image_url": "/api/pin-image/B083N1H6P7",
    "primary_image_url": "/api/pin-image/B083N1H6P7",
    "pin_image_url": null,
    "has_pin": false,
    "category": "beauty"
  },
  {
    "asin": "B0CM4B43DZ",
    "name": "La Roche-Posay Mela B3 Dark Spot Serum",
    "price": 44.99,
    "rating": 4.3,
    "review_count": 3800,
    "affiliate_url": "https://www.amazon.com/dp/B0CM4B43DZ?tag=mintbrooks-20",
    "image_url": "/api/pin-image/B0CM4B43DZ",
    "primary_image_url": "/api/pin-image/B0CM4B43DZ",
    "pin_image_url": null,
    "has_pin": false,
    "category": "beauty"
  },
  {
    "asin": "B0DM3JH5PX",
    "name": "Caudalie Premier Cru Anti-Aging Serum",
    "price": 129.0,
    "rating": 4.6,
    "review_count": 2100,
    "affiliate_url": "https://www.amazon.com/dp/B0DM3JH5PX?tag=mintbrooks-20",
    "image_url": "/api/pin-image/B0DM3JH5PX",
    "primary_image_url": "/api/pin-image/B0DM3JH5PX",
    "pin_image_url": null,
    "has_pin": false,
    "category": "beauty"
  },
  {
    "asin": "B08T8L371P",
    "name": "Glow Recipe Watermelon Niacinamide Dew Drops",
    "price": 36.0,
    "rating": 4.6,
    "review_count": 9400,
    "affiliate_url": "https://www.amazon.com/dp/B08T8L371P?tag=mintbrooks-20",
    "image_url": "/api/pin-image/B08T8L371P",
    "primary_image_url": "/api/pin-image/B08T8L371P",
    "pin_image_url": null,
    "has_pin": false,
    "category": "beauty"
  },
  {
    "asin": "B0FP4WJXD5",
    "name": "Advanced Retino-Mela Serum HPR Retinol",
    "price": 31.9,
    "rating": 4.5,
    "review_count": 1800,
    "affiliate_url": "https://www.amazon.com/dp/B0FP4WJXD5?tag=mintbrooks-20",
    "image_url": "/api/pin-image/B0FP4WJXD5",
    "primary_image_url": "/api/pin-image/B0FP4WJXD5",
    "pin_image_url": null,
    "has_pin": false,
    "category": "beauty"
  },
  {
    "asin": "B0CTC25796",
    "name": "Beauty of Joseon Revive Eye Serum",
    "price": 32.5,
    "rating": 4.3,
    "review_count": 4200,
    "affiliate_url": "https://www.amazon.com/dp/B0CTC25796?tag=mintbrooks-20",
    "image_url": "/api/pin-image/B0CTC25796",
    "primary_image_url": "/api/pin-image/B0CTC25796",
    "pin_image_url": null,
    "has_pin": false,
    "category": "beauty"
  },
  {
    "asin": "B08YZ8219S",
    "name": "Eight Saints Cloud Whip Vitamin C Moisturizer",
    "price": 33.0,
    "rating": 4.7,
    "review_count": 3600,
    "affiliate_url": "https://www.amazon.com/dp/B08YZ8219S?tag=mintbrooks-20",
    "image_url": "/api/pin-image/B08YZ8219S",
    "primary_image_url": "/api/pin-image/B08YZ8219S",
    "pin_image_url": null,
    "has_pin": false,
    "category": "beauty"
  },
  {
    "asin": "B0CQ788GT3",
    "name": "ILIA The Base Face Milk Essence",
    "price": 28.0,
    "rating": 4.5,
    "review_count": 2900,
    "affiliate_url": "https://www.amazon.com/dp/B0CQ788GT3?tag=mintbrooks-20",
    "image_url": "/api/pin-image/B0CQ788GT3",
    "primary_image_url": "/api/pin-image/B0CQ788GT3",
    "pin_image_url": null,
    "has_pin": false,
    "category": "beauty"
  },
  {
    "asin": "B01MFAX2GE",
    "name": "Ursa Major Golden Hour Face Moisturizer",
    "price": 54.0,
    "rating": 4.3,
    "review_count": 1500,
    "affiliate_url": "https://www.amazon.com/dp/B01MFAX2GE?tag=mintbrooks-20",
    "image_url": "/api/pin-image/B01MFAX2GE",
    "primary_image_url": "/api/pin-image/B01MFAX2GE",
    "pin_image_url": null,
    "has_pin": false,
    "category": "beauty"
  },
  {
    "asin": "B018A0BO92",
    "name": "Youth To The People Superfood Facial Cleanser",
    "price": 39.0,
    "rating": 4.6,
    "review_count": 18000,
    "affiliate_url": "https://www.amazon.com/dp/B018A0BO92?tag=mintbrooks-20",
    "image_url": "/api/pin-image/B018A0BO92",
    "primary_image_url": "/api/pin-image/B018A0BO92",
    "pin_image_url": null,
    "has_pin": false,
    "category": "beauty"
  },
  {
    "asin": "B0B75XKWL3",
    "name": "Brandefy Superfood Face Wash",
    "price": 29.0,
    "rating": 4.4,
    "review_count": 2200,
    "affiliate_url": "https://www.amazon.com/dp/B0B75XKWL3?tag=mintbrooks-20",
    "image_url": "/api/pin-image/B0B75XKWL3",
    "primary_image_url": "/api/pin-image/B0B75XKWL3",
    "pin_image_url": null,
    "has_pin": false,
    "category": "beauty"
  },
  {
    "asin": "B08YS1YGFR",
    "name": "Eight Saints Down To Earth Mud Gel Face Wash",
    "price": 33.0,
    "rating": 4.7,
    "review_count": 2800,
    "affiliate_url": "https://www.amazon.com/dp/B08YS1YGFR?tag=mintbrooks-20",
    "image_url": "/api/pin-image/B08YS1YGFR",
    "primary_image_url": "/api/pin-image/B08YS1YGFR",
    "pin_image_url": null,
    "has_pin": false,
    "category": "beauty"
  },
  {
    "asin": "B0F384Y1KR",
    "name": "Anua 3-Step Glass Skin Beginner Set",
    "price": 45.0,
    "rating": 4.5,
    "review_count": 3100,
    "affiliate_url": "https://www.amazon.com/dp/B0F384Y1KR?tag=mintbrooks-20",
    "image_url": "/api/pin-image/B0F384Y1KR",
    "primary_image_url": "/api/pin-image/B0F384Y1KR",
    "pin_image_url": null,
    "has_pin": false,
    "category": "beauty"
  },
  {
    "asin": "B0BKQ451Z6",
    "name": "Peach & Lily Glass Skin Discovery Kit",
    "price": 39.0,
    "rating": 4.5,
    "review_count": 4800,
    "affiliate_url": "https://www.amazon.com/dp/B0BKQ451Z6?tag=mintbrooks-20",
    "image_url": "/api/pin-image/B0BKQ451Z6",
    "primary_image_url": "/api/pin-image/B0BKQ451Z6",
    "pin_image_url": null,
    "has_pin": false,
    "category": "beauty"
  },
  {
    "asin": "B0FKB5BTSN",
    "name": "mixsoon Glass Skin Suit Case Set",
    "price": 45.0,
    "rating": 4.5,
    "review_count": 1900,
    "affiliate_url": "https://www.amazon.com/dp/B0FKB5BTSN?tag=mintbrooks-20",
    "image_url": "/api/pin-image/B0FKB5BTSN",
    "primary_image_url": "/api/pin-image/B0FKB5BTSN",
    "pin_image_url": null,
    "has_pin": false,
    "category": "beauty"
  },
  {
    "asin": "B073MW6XCG",
    "name": "Harvest Natural Beauty Liquid Foundation",
    "price": 29.0,
    "rating": 4.3,
    "review_count": 1200,
    "affiliate_url": "https://www.amazon.com/dp/B073MW6XCG?tag=mintbrooks-20",
    "image_url": "/api/pin-image/B073MW6XCG",
    "primary_image_url": "/api/pin-image/B073MW6XCG",
    "pin_image_url": null,
    "has_pin": false,
    "category": "beauty"
  },
  {
    "asin": "B0B6Q7DZ8P",
    "name": "Jerome Alexander MagicMinerals AirBrush Foundation",
    "price": 29.99,
    "rating": 4.3,
    "review_count": 8900,
    "affiliate_url": "https://www.amazon.com/dp/B0B6Q7DZ8P?tag=mintbrooks-20",
    "image_url": "/api/pin-image/B0B6Q7DZ8P",
    "primary_image_url": "/api/pin-image/B0B6Q7DZ8P",
    "pin_image_url": null,
    "has_pin": false,
    "category": "beauty"
  },
  {
    "asin": "B07DL1ZQ82",
    "name": "Clinique Even Better Makeup Liquid Foundation",
    "price": 29.25,
    "rating": 4.7,
    "review_count": 24000,
    "affiliate_url": "https://www.amazon.com/dp/B07DL1ZQ82?tag=mintbrooks-20",
    "image_url": "/api/pin-image/B07DL1ZQ82",
    "primary_image_url": "/api/pin-image/B07DL1ZQ82",
    "pin_image_url": null,
    "has_pin": false,
    "category": "beauty"
  },
  {
    "asin": "B0CN818LG8",
    "name": "bareMinerals Barepro Performance Wear Foundation",
    "price": 37.4,
    "rating": 4.4,
    "review_count": 5600,
    "affiliate_url": "https://www.amazon.com/dp/B0CN818LG8?tag=mintbrooks-20",
    "image_url": "/api/pin-image/B0CN818LG8",
    "primary_image_url": "/api/pin-image/B0CN818LG8",
    "pin_image_url": null,
    "has_pin": false,
    "category": "beauty"
  },
  {
    "asin": "B0B4HKNDLQ",
    "name": "Sol de Janeiro Jet Set Travel Shower Kit",
    "price": 34.0,
    "rating": 4.7,
    "review_count": 12000,
    "affiliate_url": "https://www.amazon.com/dp/B0B4HKNDLQ?tag=mintbrooks-20",
    "image_url": "/api/pin-image/B0B4HKNDLQ",
    "primary_image_url": "/api/pin-image/B0B4HKNDLQ",
    "pin_image_url": null,
    "has_pin": false,
    "category": "beauty"
  },
  {
    "asin": "B08Z5X1L1S",
    "name": "Beauty & Personal Care Gift Set for Women",
    "price": 34.99,
    "rating": 4.6,
    "review_count": 7800,
    "affiliate_url": "https://www.amazon.com/dp/B08Z5X1L1S?tag=mintbrooks-20",
    "image_url": "/api/pin-image/B08Z5X1L1S",
    "primary_image_url": "/api/pin-image/B08Z5X1L1S",
    "pin_image_url": null,
    "has_pin": false,
    "category": "beauty"
  },
  {
    "asin": "B089SBNKXM",
    "name": "ZAAINA Spa Gift Set for Her",
    "price": 74.99,
    "rating": 4.7,
    "review_count": 3400,
    "affiliate_url": "https://www.amazon.com/dp/B089SBNKXM?tag=mintbrooks-20",
    "image_url": "/api/pin-image/B089SBNKXM",
    "primary_image_url": "/api/pin-image/B089SBNKXM",
    "pin_image_url": null,
    "has_pin": false,
    "category": "beauty"
  },
  {
    "asin": "B0852SZ4XN",
    "name": "Too Faced Born This Way Natural Nudes Palette",
    "price": 38.88,
    "rating": 4.6,
    "review_count": 9200,
    "affiliate_url": "https://www.amazon.com/dp/B0852SZ4XN?tag=mintbrooks-20",
    "image_url": "/api/pin-image/B0852SZ4XN",
    "primary_image_url": "/api/pin-image/B0852SZ4XN",
    "pin_image_url": null,
    "has_pin": false,
    "category": "beauty"
  },
  {
    "asin": "B0CK66B44Z",
    "name": "ColourPop Smoke N Roses Eyeshadow Palette",
    "price": 28.0,
    "rating": 4.6,
    "review_count": 4100,
    "affiliate_url": "https://www.amazon.com/dp/B0CK66B44Z?tag=mintbrooks-20",
    "image_url": "/api/pin-image/B0CK66B44Z",
    "primary_image_url": "/api/pin-image/B0CK66B44Z",
    "pin_image_url": null,
    "has_pin": false,
    "category": "beauty"
  },
  {
    "asin": "B0F5LHYS9D",
    "name": "tarte Tartelette In Bloom Palette",
    "price": 49.0,
    "rating": 4.5,
    "review_count": 6700,
    "affiliate_url": "https://www.amazon.com/dp/B0F5LHYS9D?tag=mintbrooks-20",
    "image_url": "/api/pin-image/B0F5LHYS9D",
    "primary_image_url": "/api/pin-image/B0F5LHYS9D",
    "pin_image_url": null,
    "has_pin": false,
    "category": "beauty"
  },
  {
    "asin": "B0FGDYNSY8",
    "name": "Charlotte Tilbury Luxury Eyeshadow Palette",
    "price": 58.0,
    "rating": 4.4,
    "review_count": 3300,
    "affiliate_url": "https://www.amazon.com/dp/B0FGDYNSY8?tag=mintbrooks-20",
    "image_url": "/api/pin-image/B0FGDYNSY8",
    "primary_image_url": "/api/pin-image/B0FGDYNSY8",
    "pin_image_url": null,
    "has_pin": false,
    "category": "beauty"
  },
  {
    "asin": "B0DV8Z4L8X",
    "name": "ColourPop Stone Cold Fox Eyeshadow Palette",
    "price": 28.0,
    "rating": 4.6,
    "review_count": 2800,
    "affiliate_url": "https://www.amazon.com/dp/B0DV8Z4L8X?tag=mintbrooks-20",
    "image_url": "/api/pin-image/B0DV8Z4L8X",
    "primary_image_url": "/api/pin-image/B0DV8Z4L8X",
    "pin_image_url": null,
    "has_pin": false,
    "category": "beauty"
  },
  {
    "asin": "B0DK8YV2Y9",
    "name": "MAANGE 20Pcs Makeup Brush Set",
    "price": 30.58,
    "rating": 4.6,
    "review_count": 15000,
    "affiliate_url": "https://www.amazon.com/dp/B0DK8YV2Y9?tag=mintbrooks-20",
    "image_url": "/api/pin-image/B0DK8YV2Y9",
    "primary_image_url": "/api/pin-image/B0DK8YV2Y9",
    "pin_image_url": null,
    "has_pin": false,
    "category": "beauty"
  },
  {
    "asin": "B07H2WR5VV",
    "name": "DUcare Professional Makeup Brushes 27Pcs",
    "price": 29.99,
    "rating": 4.7,
    "review_count": 21000,
    "affiliate_url": "https://www.amazon.com/dp/B07H2WR5VV?tag=mintbrooks-20",
    "image_url": "/api/pin-image/B07H2WR5VV",
    "primary_image_url": "/api/pin-image/B07H2WR5VV",
    "pin_image_url": null,
    "has_pin": false,
    "category": "beauty"
  },
  {
    "asin": "B0F88GMTNL",
    "name": "Bueart Design 32Pcs PRO Makeup Brushes",
    "price": 47.99,
    "rating": 4.8,
    "review_count": 4200,
    "affiliate_url": "https://www.amazon.com/dp/B0F88GMTNL?tag=mintbrooks-20",
    "image_url": "/api/pin-image/B0F88GMTNL",
    "primary_image_url": "/api/pin-image/B0F88GMTNL",
    "pin_image_url": null,
    "has_pin": false,
    "category": "beauty"
  },
  {
    "asin": "B0725W1D66",
    "name": "Anastasia Beverly Hills Blush Trio",
    "price": 30.0,
    "rating": 4.6,
    "review_count": 7800,
    "affiliate_url": "https://www.amazon.com/dp/B0725W1D66?tag=mintbrooks-20",
    "image_url": "/api/pin-image/B0725W1D66",
    "primary_image_url": "/api/pin-image/B0725W1D66",
    "pin_image_url": null,
    "has_pin": false,
    "category": "beauty"
  },
  {
    "asin": "B01LMMZY6O",
    "name": "IT Cosmetics CC+ Cream Foundation SPF 50+",
    "price": 39.0,
    "rating": 4.5,
    "review_count": 38000,
    "affiliate_url": "https://www.amazon.com/dp/B01LMMZY6O?tag=mintbrooks-20",
    "image_url": "/api/pin-image/B01LMMZY6O",
    "primary_image_url": "/api/pin-image/B01LMMZY6O",
    "pin_image_url": null,
    "has_pin": false,
    "category": "beauty"
  },
  {
    "asin": "B01MFAX2GE",
    "name": "Ursa Major Golden Hour Face Moisturizer",
    "price": 54.0,
    "rating": 4.3,
    "review_count": 1500,
    "affiliate_url": "https://www.amazon.com/dp/B01MFAX2GE?tag=mintbrooks-20",
    "image_url": "/api/pin-image/B01MFAX2GE",
    "primary_image_url": "/api/pin-image/B01MFAX2GE",
    "pin_image_url": null,
    "has_pin": false,
    "category": "beauty"
  },
  {
    "asin": "B07VR1NDSQ",
    "name": "Olaplex No. 7 Bonding Oil",
    "price": 32.0,
    "rating": 4.7,
    "review_count": 45000,
    "affiliate_url": "https://www.amazon.com/dp/B07VR1NDSQ?tag=mintbrooks-20",
    "image_url": "/api/pin-image/B07VR1NDSQ",
    "primary_image_url": "/api/pin-image/B07VR1NDSQ",
    "pin_image_url": null,
    "has_pin": false,
    "category": "beauty"
  },
  {
    "asin": "B0DQV1FQ49",
    "name": "Kerastase Gloss Absolu Glaze Drops",
    "price": 39.0,
    "rating": 4.7,
    "review_count": 3200,
    "affiliate_url": "https://www.amazon.com/dp/B0DQV1FQ49?tag=mintbrooks-20",
    "image_url": "/api/pin-image/B0DQV1FQ49",
    "primary_image_url": "/api/pin-image/B0DQV1FQ49",
    "pin_image_url": null,
    "has_pin": false,
    "category": "beauty"
  },
  {
    "asin": "B0013VY4AM",
    "name": "Kenra Platinum Silkening Gloss",
    "price": 29.0,
    "rating": 4.6,
    "review_count": 8900,
    "affiliate_url": "https://www.amazon.com/dp/B0013VY4AM?tag=mintbrooks-20",
    "image_url": "/api/pin-image/B0013VY4AM",
    "primary_image_url": "/api/pin-image/B0013VY4AM",
    "pin_image_url": null,
    "has_pin": false,
    "category": "beauty"
  },
  {
    "asin": "B0F2QZQWDN",
    "name": "Kerastase Nutritive 8H Magic Night Serum",
    "price": 32.0,
    "rating": 4.6,
    "review_count": 2100,
    "affiliate_url": "https://www.amazon.com/dp/B0F2QZQWDN?tag=mintbrooks-20",
    "image_url": "/api/pin-image/B0F2QZQWDN",
    "primary_image_url": "/api/pin-image/B0F2QZQWDN",
    "pin_image_url": null,
    "has_pin": false,
    "category": "beauty"
  },
  {
    "asin": "B0BZZJWGPQ",
    "name": "Kerastase Nutritive 8H Magic Night Serum (Large)",
    "price": 62.0,
    "rating": 4.6,
    "review_count": 2100,
    "affiliate_url": "https://www.amazon.com/dp/B0BZZJWGPQ?tag=mintbrooks-20",
    "image_url": "/api/pin-image/B0BZZJWGPQ",
    "primary_image_url": "/api/pin-image/B0BZZJWGPQ",
    "pin_image_url": null,
    "has_pin": false,
    "category": "beauty"
  },
  {
    "asin": "B0B137RLYG",
    "name": "OUAI Scalp Serum",
    "price": 54.0,
    "rating": 4.4,
    "review_count": 5600,
    "affiliate_url": "https://www.amazon.com/dp/B0B137RLYG?tag=mintbrooks-20",
    "image_url": "/api/pin-image/B0B137RLYG",
    "primary_image_url": "/api/pin-image/B0B137RLYG",
    "pin_image_url": null,
    "has_pin": false,
    "category": "beauty"
  },
  {
    "asin": "B086TPQJTT",
    "name": "Kerastase Genesis Hair Serum",
    "price": 64.0,
    "rating": 4.4,
    "review_count": 4100,
    "affiliate_url": "https://www.amazon.com/dp/B086TPQJTT?tag=mintbrooks-20",
    "image_url": "/api/pin-image/B086TPQJTT",
    "primary_image_url": "/api/pin-image/B086TPQJTT",
    "pin_image_url": null,
    "has_pin": false,
    "category": "beauty"
  },
  {
    "asin": "B099XMVSB1",
    "name": "L'Or\u00e9al Professionnel Absolut Repair Hair Mask",
    "price": 48.0,
    "rating": 4.7,
    "review_count": 8700,
    "affiliate_url": "https://www.amazon.com/dp/B099XMVSB1?tag=mintbrooks-20",
    "image_url": "/api/pin-image/B099XMVSB1",
    "primary_image_url": "/api/pin-image/B099XMVSB1",
    "pin_image_url": null,
    "has_pin": false,
    "category": "beauty"
  },
  {
    "asin": "B07H3GBSC3",
    "name": "amika Soulfood Nourishing Mask",
    "price": 36.0,
    "rating": 4.7,
    "review_count": 12000,
    "affiliate_url": "https://www.amazon.com/dp/B07H3GBSC3?tag=mintbrooks-20",
    "image_url": "/api/pin-image/B07H3GBSC3",
    "primary_image_url": "/api/pin-image/B07H3GBSC3",
    "pin_image_url": null,
    "has_pin": false,
    "category": "beauty"
  },
  {
    "asin": "B09HR5KSR8",
    "name": "K18 Leave-In Molecular Repair Hair Mask",
    "price": 29.0,
    "rating": 4.3,
    "review_count": 19000,
    "affiliate_url": "https://www.amazon.com/dp/B09HR5KSR8?tag=mintbrooks-20",
    "image_url": "/api/pin-image/B09HR5KSR8",
    "primary_image_url": "/api/pin-image/B09HR5KSR8",
    "pin_image_url": null,
    "has_pin": false,
    "category": "beauty"
  },
  {
    "asin": "B089VRBZY6",
    "name": "Simple&Opulence 100% Linen Duvet Cover Set",
    "price": 137.5,
    "rating": 4.6,
    "review_count": 8200,
    "affiliate_url": "https://www.amazon.com/dp/B089VRBZY6?tag=mintbrooks-20",
    "image_url": "/api/pin-image/B089VRBZY6",
    "primary_image_url": "/api/pin-image/B089VRBZY6",
    "pin_image_url": null,
    "has_pin": false,
    "category": "home-decor"
  },
  {
    "asin": "B0D3HG2GQ2",
    "name": "Andency Linen Comforter Set Queen",
    "price": 45.99,
    "rating": 4.5,
    "review_count": 5400,
    "affiliate_url": "https://www.amazon.com/dp/B0D3HG2GQ2?tag=mintbrooks-20",
    "image_url": "/api/pin-image/B0D3HG2GQ2",
    "primary_image_url": "/api/pin-image/B0D3HG2GQ2",
    "pin_image_url": null,
    "has_pin": false,
    "category": "home-decor"
  },
  {
    "asin": "B0FJRZQYHG",
    "name": "Bedsure Waffle Duvet Cover Queen",
    "price": 89.99,
    "rating": 4.4,
    "review_count": 6100,
    "affiliate_url": "https://www.amazon.com/dp/B0FJRZQYHG?tag=mintbrooks-20",
    "image_url": "/api/pin-image/B0FJRZQYHG",
    "primary_image_url": "/api/pin-image/B0FJRZQYHG",
    "pin_image_url": null,
    "has_pin": false,
    "category": "home-decor"
  },
  {
    "asin": "B0BR728TB6",
    "name": "L'AGRATY Chunky Knit Throw Blanket",
    "price": 31.33,
    "rating": 4.4,
    "review_count": 9800,
    "affiliate_url": "https://www.amazon.com/dp/B0BR728TB6?tag=mintbrooks-20",
    "image_url": "/api/pin-image/B0BR728TB6",
    "primary_image_url": "/api/pin-image/B0BR728TB6",
    "pin_image_url": null,
    "has_pin": false,
    "category": "home-decor"
  },
  {
    "asin": "B0D264M84J",
    "name": "Chunky Knit Throw Blanket Cream",
    "price": 31.18,
    "rating": 4.5,
    "review_count": 7300,
    "affiliate_url": "https://www.amazon.com/dp/B0D264M84J?tag=mintbrooks-20",
    "image_url": "/api/pin-image/B0D264M84J",
    "primary_image_url": "/api/pin-image/B0D264M84J",
    "pin_image_url": null,
    "has_pin": false,
    "category": "home-decor"
  },
  {
    "asin": "B0DCZMZ1LF",
    "name": "BENVWE Fluffy Faux Fur Throw Blanket",
    "price": 42.99,
    "rating": 4.8,
    "review_count": 14500,
    "affiliate_url": "https://www.amazon.com/dp/B0DCZMZ1LF?tag=mintbrooks-20",
    "image_url": "/api/pin-image/B0DCZMZ1LF",
    "primary_image_url": "/api/pin-image/B0DCZMZ1LF",
    "pin_image_url": null,
    "has_pin": false,
    "category": "home-decor"
  },
  {
    "asin": "B0D22SN9Y1",
    "name": "Wemore Fleece Weighted Blanket 15lbs",
    "price": 49.98,
    "rating": 4.7,
    "review_count": 11200,
    "affiliate_url": "https://www.amazon.com/dp/B0D22SN9Y1?tag=mintbrooks-20",
    "image_url": "/api/pin-image/B0D22SN9Y1",
    "primary_image_url": "/api/pin-image/B0D22SN9Y1",
    "pin_image_url": null,
    "has_pin": false,
    "category": "home-decor"
  },
  {
    "asin": "B092LZLLGF",
    "name": "yescool Weighted Blanket 20lbs",
    "price": 43.99,
    "rating": 4.5,
    "review_count": 8600,
    "affiliate_url": "https://www.amazon.com/dp/B092LZLLGF?tag=mintbrooks-20",
    "image_url": "/api/pin-image/B092LZLLGF",
    "primary_image_url": "/api/pin-image/B092LZLLGF",
    "pin_image_url": null,
    "has_pin": false,
    "category": "home-decor"
  },
  {
    "asin": "B0869NWJ6Q",
    "name": "Uttermara Weighted Blankets 15lbs",
    "price": 47.98,
    "rating": 4.7,
    "review_count": 9900,
    "affiliate_url": "https://www.amazon.com/dp/B0869NWJ6Q?tag=mintbrooks-20",
    "image_url": "/api/pin-image/B0869NWJ6Q",
    "primary_image_url": "/api/pin-image/B0869NWJ6Q",
    "pin_image_url": null,
    "has_pin": false,
    "category": "home-decor"
  },
  {
    "asin": "B0F23VR2S4",
    "name": "Flower Candle Warmer Lamp with Timer",
    "price": 30.98,
    "rating": 4.8,
    "review_count": 18700,
    "affiliate_url": "https://www.amazon.com/dp/B0F23VR2S4?tag=mintbrooks-20",
    "image_url": "/api/pin-image/B0F23VR2S4",
    "primary_image_url": "/api/pin-image/B0F23VR2S4",
    "pin_image_url": null,
    "has_pin": false,
    "category": "home-decor"
  },
  {
    "asin": "B0DCNZT2GT",
    "name": "Electric Candle Warmer Lamp Black",
    "price": 29.99,
    "rating": 4.6,
    "review_count": 12300,
    "affiliate_url": "https://www.amazon.com/dp/B0DCNZT2GT?tag=mintbrooks-20",
    "image_url": "/api/pin-image/B0DCNZT2GT",
    "primary_image_url": "/api/pin-image/B0DCNZT2GT",
    "pin_image_url": null,
    "has_pin": false,
    "category": "home-decor"
  },
  {
    "asin": "B07C7PW3PC",
    "name": "Anova Culinary Sous Vide Precision Cooker Nano",
    "price": 62.72,
    "rating": 4.6,
    "review_count": 32000,
    "affiliate_url": "https://www.amazon.com/dp/B07C7PW3PC?tag=mintbrooks-20",
    "image_url": "/api/pin-image/B07C7PW3PC",
    "primary_image_url": "/api/pin-image/B07C7PW3PC",
    "pin_image_url": null,
    "has_pin": false,
    "category": "kitchen"
  },
  {
    "asin": "B07RNWJZNR",
    "name": "INKBIRD WiFi Sous Vide Cooker ISV-100W",
    "price": 95.99,
    "rating": 4.5,
    "review_count": 8900,
    "affiliate_url": "https://www.amazon.com/dp/B07RNWJZNR?tag=mintbrooks-20",
    "image_url": "/api/pin-image/B07RNWJZNR",
    "primary_image_url": "/api/pin-image/B07RNWJZNR",
    "pin_image_url": null,
    "has_pin": false,
    "category": "kitchen"
  },
  {
    "asin": "B0F8N5W8BJ",
    "name": "26QT Large Sous Vide Container with Lid",
    "price": 81.99,
    "rating": 4.8,
    "review_count": 3200,
    "affiliate_url": "https://www.amazon.com/dp/B0F8N5W8BJ?tag=mintbrooks-20",
    "image_url": "/api/pin-image/B0F8N5W8BJ",
    "primary_image_url": "/api/pin-image/B0F8N5W8BJ",
    "pin_image_url": null,
    "has_pin": false,
    "category": "kitchen"
  },
  {
    "asin": "B0CYJDVT31",
    "name": "Bella 4Qt Slim Air Fryer",
    "price": 49.99,
    "rating": 4.6,
    "review_count": 7800,
    "affiliate_url": "https://www.amazon.com/dp/B0CYJDVT31?tag=mintbrooks-20",
    "image_url": "/api/pin-image/B0CYJDVT31",
    "primary_image_url": "/api/pin-image/B0CYJDVT31",
    "pin_image_url": null,
    "has_pin": false,
    "category": "kitchen"
  },
  {
    "asin": "B0DC11YH4J",
    "name": "CHEFMAN 2Qt Mini Air Fryer",
    "price": 44.97,
    "rating": 4.5,
    "review_count": 5600,
    "affiliate_url": "https://www.amazon.com/dp/B0DC11YH4J?tag=mintbrooks-20",
    "image_url": "/api/pin-image/B0DC11YH4J",
    "primary_image_url": "/api/pin-image/B0DC11YH4J",
    "pin_image_url": null,
    "has_pin": false,
    "category": "kitchen"
  },
  {
    "asin": "B0C33CHG99",
    "name": "Cosori 9-in-1 TurboBlaze Air Fryer 6Qt",
    "price": 89.87,
    "rating": 4.8,
    "review_count": 21000,
    "affiliate_url": "https://www.amazon.com/dp/B0C33CHG99?tag=mintbrooks-20",
    "image_url": "/api/pin-image/B0C33CHG99",
    "primary_image_url": "/api/pin-image/B0C33CHG99",
    "pin_image_url": null,
    "has_pin": false,
    "category": "kitchen"
  },
  {
    "asin": "B08ZK5WDWN",
    "name": "Vtopmart Airtight Food Storage Containers",
    "price": 29.43,
    "rating": 4.7,
    "review_count": 42000,
    "affiliate_url": "https://www.amazon.com/dp/B08ZK5WDWN?tag=mintbrooks-20",
    "image_url": "/api/pin-image/B08ZK5WDWN",
    "primary_image_url": "/api/pin-image/B08ZK5WDWN",
    "pin_image_url": null,
    "has_pin": false,
    "category": "kitchen"
  },
  {
    "asin": "B0DDKK7DWH",
    "name": "GHWIE Bamboo Bread Box for Kitchen Counter",
    "price": 36.89,
    "rating": 4.6,
    "review_count": 6200,
    "affiliate_url": "https://www.amazon.com/dp/B0DDKK7DWH?tag=mintbrooks-20",
    "image_url": "/api/pin-image/B0DDKK7DWH",
    "primary_image_url": "/api/pin-image/B0DDKK7DWH",
    "pin_image_url": null,
    "has_pin": false,
    "category": "kitchen"
  },
  {
    "asin": "B0FBLNF2KD",
    "name": "Potato and Onion Storage Bin Set",
    "price": 41.99,
    "rating": 4.8,
    "review_count": 4100,
    "affiliate_url": "https://www.amazon.com/dp/B0FBLNF2KD?tag=mintbrooks-20",
    "image_url": "/api/pin-image/B0FBLNF2KD",
    "primary_image_url": "/api/pin-image/B0FBLNF2KD",
    "pin_image_url": null,
    "has_pin": false,
    "category": "kitchen"
  },
  {
    "asin": "B0GFW1L9V1",
    "name": "66Ft Automatic Drip Irrigation Kit",
    "price": 29.99,
    "rating": 5.0,
    "review_count": 890,
    "affiliate_url": "https://www.amazon.com/dp/B0GFW1L9V1?tag=mintbrooks-20",
    "image_url": "/api/pin-image/B0GFW1L9V1",
    "primary_image_url": "/api/pin-image/B0GFW1L9V1",
    "pin_image_url": null,
    "has_pin": false,
    "category": "home-decor"
  },
  {
    "asin": "B0DYJQ6M79",
    "name": "250FT Drip Irrigation Kit Quick-Connect",
    "price": 59.99,
    "rating": 4.5,
    "review_count": 2100,
    "affiliate_url": "https://www.amazon.com/dp/B0DYJQ6M79?tag=mintbrooks-20",
    "image_url": "/api/pin-image/B0DYJQ6M79",
    "primary_image_url": "/api/pin-image/B0DYJQ6M79",
    "pin_image_url": null,
    "has_pin": false,
    "category": "home-decor"
  },
  {
    "asin": "B0FFB991KF",
    "name": "MIXC 200Ft Drip Irrigation System",
    "price": 64.99,
    "rating": 4.5,
    "review_count": 3800,
    "affiliate_url": "https://www.amazon.com/dp/B0FFB991KF?tag=mintbrooks-20",
    "image_url": "/api/pin-image/B0FFB991KF",
    "primary_image_url": "/api/pin-image/B0FFB991KF",
    "pin_image_url": null,
    "has_pin": false,
    "category": "home-decor"
  },
  {
    "asin": "B09R98W9J5",
    "name": "WORKPRO 8-Piece Pink Garden Tool Set",
    "price": 39.55,
    "rating": 4.8,
    "review_count": 12400,
    "affiliate_url": "https://www.amazon.com/dp/B09R98W9J5?tag=mintbrooks-20",
    "image_url": "/api/pin-image/B09R98W9J5",
    "primary_image_url": "/api/pin-image/B09R98W9J5",
    "pin_image_url": null,
    "has_pin": false,
    "category": "home-decor"
  },
  {
    "asin": "B0DWHSCGRL",
    "name": "12-Piece Women's Gardening Tools Set",
    "price": 28.99,
    "rating": 4.7,
    "review_count": 6700,
    "affiliate_url": "https://www.amazon.com/dp/B0DWHSCGRL?tag=mintbrooks-20",
    "image_url": "/api/pin-image/B0DWHSCGRL",
    "primary_image_url": "/api/pin-image/B0DWHSCGRL",
    "pin_image_url": null,
    "has_pin": false,
    "category": "home-decor"
  },
  {
    "asin": "B0CQ4BYFGR",
    "name": "7-Piece Outdoor Patio Furniture Set Grey",
    "price": 299.96,
    "rating": 4.6,
    "review_count": 4300,
    "affiliate_url": "https://www.amazon.com/dp/B0CQ4BYFGR?tag=mintbrooks-20",
    "image_url": "/api/pin-image/B0CQ4BYFGR",
    "primary_image_url": "/api/pin-image/B0CQ4BYFGR",
    "pin_image_url": null,
    "has_pin": false,
    "category": "home-decor"
  },
  {
    "asin": "B07BZ5B3LS",
    "name": "Keter Unity XL Portable Outdoor Table",
    "price": 220.99,
    "rating": 4.4,
    "review_count": 8900,
    "affiliate_url": "https://www.amazon.com/dp/B07BZ5B3LS?tag=mintbrooks-20",
    "image_url": "/api/pin-image/B07BZ5B3LS",
    "primary_image_url": "/api/pin-image/B07BZ5B3LS",
    "pin_image_url": null,
    "has_pin": false,
    "category": "home-decor"
  },
  {
    "asin": "B0FKGQ8V4R",
    "name": "Outdoor Grill Cart with Storage",
    "price": 149.38,
    "rating": 4.8,
    "review_count": 2800,
    "affiliate_url": "https://www.amazon.com/dp/B0FKGQ8V4R?tag=mintbrooks-20",
    "image_url": "/api/pin-image/B0FKGQ8V4R",
    "primary_image_url": "/api/pin-image/B0FKGQ8V4R",
    "pin_image_url": null,
    "has_pin": false,
    "category": "home-decor"
  },
  {
    "asin": "B0G2ST1SYJ",
    "name": "Lab Grown Diamond Tennis Bracelet Sterling Silver",
    "price": 349.99,
    "rating": 5.0,
    "review_count": 420,
    "affiliate_url": "https://www.amazon.com/dp/B0G2ST1SYJ?tag=mintbrooks-20",
    "image_url": "/api/pin-image/B0G2ST1SYJ",
    "primary_image_url": "/api/pin-image/B0G2ST1SYJ",
    "pin_image_url": null,
    "has_pin": false,
    "category": "wellness"
  },
  {
    "asin": "B0DWNGSRMV",
    "name": "IGI Certified Lab Grown Diamond Tennis Bracelet",
    "price": 1345.0,
    "rating": 4.8,
    "review_count": 890,
    "affiliate_url": "https://www.amazon.com/dp/B0DWNGSRMV?tag=mintbrooks-20",
    "image_url": "/api/pin-image/B0DWNGSRMV",
    "primary_image_url": "/api/pin-image/B0DWNGSRMV",
    "pin_image_url": null,
    "has_pin": false,
    "category": "wellness"
  },
  {
    "asin": "B0BG6LQCCD",
    "name": "3-30 Carat Lab Grown Diamond Tennis Bracelet",
    "price": 1392.3,
    "rating": 4.4,
    "review_count": 1200,
    "affiliate_url": "https://www.amazon.com/dp/B0BG6LQCCD?tag=mintbrooks-20",
    "image_url": "/api/pin-image/B0BG6LQCCD",
    "primary_image_url": "/api/pin-image/B0BG6LQCCD",
    "pin_image_url": null,
    "has_pin": false,
    "category": "wellness"
  },
  {
    "asin": "B0F5M9793N",
    "name": "Birthday Gifts for Women Self Care Package",
    "price": 39.99,
    "rating": 4.7,
    "review_count": 6800,
    "affiliate_url": "https://www.amazon.com/dp/B0F5M9793N?tag=mintbrooks-20",
    "image_url": "/api/pin-image/B0F5M9793N",
    "primary_image_url": "/api/pin-image/B0F5M9793N",
    "pin_image_url": null,
    "has_pin": false,
    "category": "wellness"
  },
  {
    "asin": "B0G2RWQ5J5",
    "name": "14-Piece Vintage Self-Care Gift Basket",
    "price": 35.99,
    "rating": 4.5,
    "review_count": 3200,
    "affiliate_url": "https://www.amazon.com/dp/B0G2RWQ5J5?tag=mintbrooks-20",
    "image_url": "/api/pin-image/B0G2RWQ5J5",
    "primary_image_url": "/api/pin-image/B0G2RWQ5J5",
    "pin_image_url": null,
    "has_pin": false,
    "category": "wellness"
  },
  {
    "asin": "B0F8QM7XTY",
    "name": "Self Care Gifts Get Well Soon Gift Basket",
    "price": 42.99,
    "rating": 4.9,
    "review_count": 2100,
    "affiliate_url": "https://www.amazon.com/dp/B0F8QM7XTY?tag=mintbrooks-20",
    "image_url": "/api/pin-image/B0F8QM7XTY",
    "primary_image_url": "/api/pin-image/B0F8QM7XTY",
    "pin_image_url": null,
    "has_pin": false,
    "category": "wellness"
  },
  {
    "asin": "B0CWZYRC4G",
    "name": "Glow Recipe Hue Drops Bronzing Serum",
    "price": 36.0,
    "rating": 4.5,
    "review_count": 4600,
    "affiliate_url": "https://www.amazon.com/dp/B0CWZYRC4G?tag=mintbrooks-20",
    "image_url": "/api/pin-image/B0CWZYRC4G",
    "primary_image_url": "/api/pin-image/B0CWZYRC4G",
    "pin_image_url": null,
    "has_pin": false,
    "category": "wellness"
  }
]

export function getProducts(category?: string): Product[] {
  if (!category) return ALL_PRODUCTS
  return ALL_PRODUCTS.filter(p => p.category === category)
}

export function getProductsByCategory(category: string, limit = 12): Product[] {
  return getProducts(category).slice(0, limit)
}

export function getFeaturedProducts(limit = 8): Product[] {
  return ALL_PRODUCTS.slice(0, limit)
}

