/**
 * render-videos-ffmpeg.ts — VIRAL MECHANICS RENDERER v2
 *
 * What hooks Instagram and TikTok (implemented here):
 *   ✓ Ken Burns slow zoom on EVERY frame — prevents 7-second drop-off
 *   ✓ Zoom PUNCH at scene start — 9-frame fast burst (pattern interrupt)
 *   ✓ Pan direction rotation per scene/frame — eye never rests
 *   ✓ Smash cuts between scenes — no fade, no crossfade, hard cut
 *   ✓ Multi-frame scenes: each frame gets its own Ken Burns + pan dir
 *   ✓ TikTok spec: 1080×1920, H.264 CRF18, 30fps, yuv420p, faststart
 *
 * Reads pipeline-result.json. Supports:
 *   - Legacy: assets[sceneId].filePath (single frame per scene)
 *   - Multi-frame: assets[sceneId].frames[] (N frames per scene)
 *
 * Run: npx tsx scripts/render-videos-ffmpeg.ts
 */

import 'dotenv/config'
import * as fs from 'fs'
import * as path from 'path'
import { execSync } from 'child_process'

const FFMPEG = process.env.FFMPEG_PATH ?? 'ffmpeg'
const FPS    = 30
const WIDTH  = 1080
const HEIGHT = 1920

// ─── KEN BURNS PARAMETERS ──────────────────────────────────────────────────

const KB_RATE      = 0.001   // zoom units per frame — slow cinematic drift
const PUNCH_RATE   = 0.04    // zoom units per frame — aggressive scene-start punch
const PUNCH_FRAMES = 9       // how many frames the punch lasts
const MAX_ZOOM     = 1.5     // never zoom past this (avoids black bars)
const PRE_SCALE    = 8000    // pre-scale source to this width so zoompan has room

// ─── PAN DIRECTIONS ────────────────────────────────────────────────────────
// Cycle through these per (sceneIndex + frameIndex) for visual rhythm.
// Each is a different anchor + drift direction in the 8000px pre-scaled source.

const PAN_STRATEGIES = [
  { label: 'center',      x: 'iw/2-(iw/zoom/2)',         y: 'ih/2-(ih/zoom/2)' },
  { label: 'drift-right', x: 'iw/2-(iw/zoom/2)+on*2',   y: 'ih/2-(ih/zoom/2)' },
  { label: 'drift-left',  x: 'iw/2-(iw/zoom/2)-on*2',   y: 'ih/2-(ih/zoom/2)' },
  { label: 'drift-up',    x: 'iw/2-(iw/zoom/2)',         y: 'ih/2-(ih/zoom/2)-on*1.5' },
  { label: 'drift-down',  x: 'iw/2-(iw/zoom/2)',         y: 'ih/2-(ih/zoom/2)+on*1.5' },
  { label: 'upper-left',  x: 'iw/3-(iw/zoom/2)+on*1.5', y: 'ih/3-(ih/zoom/2)-on*1' },
  { label: 'lower-right', x: '2*iw/3-(iw/zoom/2)-on*1', y: '2*ih/3-(ih/zoom/2)+on*1' },
]

// ─── SCENE DURATIONS ───────────────────────────────────────────────────────

const SCENE_DURATION_MAP: Record<string, number> = {
  hook:         3,
  problem:      5,
  solution:     12,
  social_proof: 8,
  cta:          4,
}

function inferDuration(sceneId: string): number {
  const id = sceneId.toLowerCase()
  if (id.includes('hook'))                               return SCENE_DURATION_MAP.hook
  if (id.includes('problem') || id.includes('step') || id.includes('state-check'))
                                                         return SCENE_DURATION_MAP.problem
  if (id.includes('solution') || id.includes('reveal') || id.includes('approved') ||
      id.includes('education') || id.includes('walkthrough'))
                                                         return SCENE_DURATION_MAP.solution
  if (id.includes('proof') || id.includes('social'))    return SCENE_DURATION_MAP.social_proof
  if (id.includes('cta'))                               return SCENE_DURATION_MAP.cta
  return 5
}

// ─── TYPES ─────────────────────────────────────────────────────────────────

interface PipelineResult {
  remotionConfig: {
    assetMap: Record<string, string>
    sceneOrder: string[]
    outputDir: string
  }
  // enriched format (generated by generate-scene-frames.ts)
  assets?: Record<string, {
    filePath?: string
    frames?: string[]
  }>
}

// ─── FILTER BUILDER ────────────────────────────────────────────────────────

function buildZoompanVF(
  durationSecs: number,
  pan: typeof PAN_STRATEGIES[0],
  isSceneStart: boolean,
): string {
  const totalFrames = Math.round(durationSecs * FPS)

  // Punch: first PUNCH_FRAMES zoom fast, then slow KB drift
  const zExpr = isSceneStart
    ? `if(lte(on,${PUNCH_FRAMES}),min(zoom+${PUNCH_RATE},${MAX_ZOOM}),min(zoom+${KB_RATE},${MAX_ZOOM}))`
    : `min(zoom+${KB_RATE},${MAX_ZOOM})`

  return [
    `scale=${PRE_SCALE}:-1`,
    `zoompan=z='${zExpr}':x='${pan.x}':y='${pan.y}':d=${totalFrames}:s=${WIDTH}x${HEIGHT}:fps=${FPS}`,
    `setsar=1`,
  ].join(',')
}

// ─── FRAME CLIP RENDERER ───────────────────────────────────────────────────

function renderFrameClip(
  imgPath: string,
  clipPath: string,
  durationSecs: number,
  pan: typeof PAN_STRATEGIES[0],
  isSceneStart: boolean,
): void {
  const vf = buildZoompanVF(durationSecs, pan, isSceneStart)

  const cmd = [
    FFMPEG, '-y',
    '-loop', '1',
    '-i', `"${imgPath}"`,
    '-vf', `"${vf}"`,
    '-t', String(durationSecs),
    '-r', String(FPS),
    '-c:v', 'libx264',
    '-crf', '18',
    '-preset', 'fast',
    '-pix_fmt', 'yuv420p',
    `"${clipPath}"`,
  ].join(' ')

  execSync(cmd, { stdio: 'pipe' })
}

// ─── SCENE RENDERER ────────────────────────────────────────────────────────

function renderScene(
  sceneId: string,
  frames: string[],
  sceneIndex: number,
  tempDir: string,
): string | null {
  const totalDuration  = inferDuration(sceneId)
  const frameDuration  = totalDuration / frames.length
  const frameClips: string[] = []

  for (let fi = 0; fi < frames.length; fi++) {
    const imgPath = frames[fi]

    if (!fs.existsSync(imgPath)) {
      console.log(`    ⚠️  Missing: ${path.basename(imgPath)} — skipping frame`)
      continue
    }

    // Each frame gets a different pan direction — eye never rests
    const panIdx = (sceneIndex * 3 + fi) % PAN_STRATEGIES.length
    const pan    = PAN_STRATEGIES[panIdx]
    // Zoom punch only on the FIRST frame of a scene
    const punch  = fi === 0
    const clipPath = path.join(tempDir, `${sceneId}_f${String(fi).padStart(2, '0')}.mp4`)

    renderFrameClip(imgPath, clipPath, frameDuration, pan, punch)
    frameClips.push(clipPath)

    const punchLabel = punch ? ' ⚡ PUNCH' : ''
    console.log(`    ✓ frame ${fi + 1}/${frames.length} — ${frameDuration.toFixed(1)}s [${pan.label}]${punchLabel}`)
  }

  if (frameClips.length === 0) return null
  if (frameClips.length === 1) return frameClips[0]

  // Smash cut concat of frames within scene — hard cuts, no transition
  const listPath      = path.join(tempDir, `${sceneId}_frames.txt`)
  const sceneClipPath = path.join(tempDir, `${sceneId}_scene.mp4`)

  fs.writeFileSync(listPath, frameClips.map(c => `file '${c}'`).join('\n'))

  execSync([
    FFMPEG, '-y',
    '-f', 'concat', '-safe', '0',
    '-i', `"${listPath}"`,
    '-c', 'copy',
    `"${sceneClipPath}"`,
  ].join(' '), { stdio: 'pipe' })

  return sceneClipPath
}

// ─── VIDEO RENDERER ────────────────────────────────────────────────────────

function renderVideo(videoDir: string): void {
  const slug       = path.basename(videoDir)
  const resultPath = path.join(videoDir, 'pipeline-result.json')

  if (!fs.existsSync(resultPath)) {
    console.log(`  ⚠️  No pipeline-result.json in ${slug} — skipping`)
    return
  }

  const result: PipelineResult = JSON.parse(fs.readFileSync(resultPath, 'utf8'))
  const { sceneOrder, assetMap } = result.remotionConfig

  if (!sceneOrder || sceneOrder.length === 0) {
    console.log(`  ⚠️  No scenes in ${slug} — skipping`)
    return
  }

  console.log(`\n  ━━━ ${slug} ━━━`)
  console.log(`  Scenes: ${sceneOrder.join(' → ')}`)

  const tempDir = path.join(videoDir, '_tmp_render')
  fs.mkdirSync(tempDir, { recursive: true })

  const sceneClips: string[] = []

  for (let si = 0; si < sceneOrder.length; si++) {
    const sceneId = sceneOrder[si]
    let frames: string[]

    // Multi-frame format (future runs with generate-scene-frames.ts)
    if (result.assets?.[sceneId]?.frames?.length) {
      frames = result.assets[sceneId]!.frames!.filter(f => fs.existsSync(f))
    }
    // Enriched single-frame
    else if (result.assets?.[sceneId]?.filePath) {
      frames = [result.assets[sceneId]!.filePath!]
    }
    // Legacy assetMap
    else if (assetMap[sceneId]) {
      frames = [assetMap[sceneId]]
    }
    else {
      console.log(`  ⚠️  No asset for scene "${sceneId}" — skipping`)
      continue
    }

    // Filter out missing files
    frames = frames.filter(f => fs.existsSync(f))
    if (frames.length === 0) {
      console.log(`  ⚠️  All frames missing for "${sceneId}" — skipping`)
      continue
    }

    const duration = inferDuration(sceneId)
    console.log(`\n  Scene ${si + 1}/${sceneOrder.length}: ${sceneId} — ${duration}s — ${frames.length} frame${frames.length > 1 ? 's' : ''}`)

    const clip = renderScene(sceneId, frames, si, tempDir)
    if (clip) sceneClips.push(clip)
  }

  if (sceneClips.length === 0) {
    console.log(`  ✗ No usable clips for ${slug}`)
    fs.rmSync(tempDir, { recursive: true, force: true })
    return
  }

  // ── Final smash-cut concat of all scenes ───────────────────────────────
  const outputPath = path.join(videoDir, `${slug}.mp4`)

  if (sceneClips.length === 1) {
    // Single scene — copy directly with faststart
    execSync([
      FFMPEG, '-y',
      '-i', `"${sceneClips[0]}"`,
      '-c', 'copy',
      '-movflags', '+faststart',
      `"${outputPath}"`,
    ].join(' '), { stdio: 'pipe' })
  } else {
    const masterList = path.join(tempDir, '_master.txt')
    fs.writeFileSync(masterList, sceneClips.map(c => `file '${c}'`).join('\n'))

    // Re-encode final: consistent quality + faststart for mobile playback
    execSync([
      FFMPEG, '-y',
      '-f', 'concat', '-safe', '0',
      '-i', `"${masterList}"`,
      '-c:v', 'libx264',
      '-crf', '18',
      '-preset', 'medium',
      '-pix_fmt', 'yuv420p',
      '-movflags', '+faststart',
      `"${outputPath}"`,
    ].join(' '), { stdio: 'pipe' })
  }

  fs.rmSync(tempDir, { recursive: true, force: true })

  const sizeMb = (fs.statSync(outputPath).size / 1024 / 1024).toFixed(1)
  console.log(`\n  ✓ ${slug}.mp4 — ${sizeMb} MB`)
  console.log(`    ${outputPath}`)
}

// ─── MAIN ──────────────────────────────────────────────────────────────────

function main() {
  const baseDir = path.resolve(__dirname, '../output/drive-credit')

  if (!fs.existsSync(baseDir)) {
    console.error(`Output dir not found: ${baseDir}`)
    process.exit(1)
  }

  const videoDirs = fs.readdirSync(baseDir)
    .map(d => path.join(baseDir, d))
    .filter(d => fs.statSync(d).isDirectory())

  console.log('\n╔══════════════════════════════════════════════════════════════╗')
  console.log('║     VIRAL VIDEO RENDERER — DriveCredit TikTok              ║')
  console.log('║     Ken Burns + Zoom Punch + Smash Cuts                    ║')
  console.log(`║     ${videoDirs.length} video${videoDirs.length !== 1 ? 's' : ''} queued                                         ║`)
  console.log('╚══════════════════════════════════════════════════════════════╝')

  for (const dir of videoDirs) {
    try {
      renderVideo(dir)
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err)
      console.error(`\n  ✗ FAILED: ${path.basename(dir)}`)
      console.error(`    ${msg.slice(0, 400)}`)
    }
  }

  // ── Summary ───────────────────────────────────────────────────────────
  const mp4s = videoDirs
    .map(d => path.join(d, `${path.basename(d)}.mp4`))
    .filter(f => fs.existsSync(f))

  console.log('\n╔══════════════════════════════════════════════════════════════╗')
  console.log('║                    RENDER COMPLETE                         ║')
  console.log('╚══════════════════════════════════════════════════════════════╝')

  for (const mp4 of mp4s) {
    const sizeMb = (fs.statSync(mp4).size / 1024 / 1024).toFixed(1)
    console.log(`  ✓ ${path.basename(mp4)} — ${sizeMb} MB`)
    console.log(`    ${path.dirname(mp4)}/`)
  }

  console.log(`\n  ${mp4s.length} / ${videoDirs.length} rendered`)

  if (mp4s.length < videoDirs.length) {
    console.log('\n  TIP: Run generate-scene-frames.ts first to add multi-frame')
    console.log('  scenes — richer source material, more cinematic output.')
  }
}

main()
