import { MetadataRoute } from 'next'
import { ARTICLES } from '@/lib/lifestyle/articles'
import { EDITORIAL_SLUGS, AFFILIATE_SLUGS } from '@/lib/articles-manifest'
import { routing } from '@/i18n/routing'
import { execSync } from 'child_process'
import fs from 'fs'
import path from 'path'

// Prerender at build so fs.readdirSync(public/articles/...) runs on the build
// host (where the repo filesystem exists) rather than on the Cloudflare Worker
// (where it doesn't). Without this the editorial + affiliate static articles
// silently drop out of the sitemap at runtime.
export const dynamic = 'force-static'

// Editorial + affiliate slugs come from a committed manifest file that is
// regenerated by the publishing pipeline. A direct import reliably bundles
// into the Worker (fs.readdirSync doesn't work at Worker runtime, and
// module-level enumeration via fs silently returned empty on this setup).
const EDITORIAL_FILES = EDITORIAL_SLUGS.map(slug => ({ slug, mtime: new Date() }))
const AFFILIATE_FILES = AFFILIATE_SLUGS.map(slug => ({ slug, mtime: new Date() }))

// Per-URL lastmod: Google weighs this as a freshness signal. We derive it from
// the real file mtime (git commit time when available; filesystem mtime as
// fallback) so the value reflects actual content changes, not build time.
function gitMtime(relPath: string): Date {
  try {
    const iso = execSync(`git log -1 --format=%cI -- "${relPath}"`, {
      cwd: process.cwd(),
      encoding: 'utf8',
      stdio: ['ignore', 'pipe', 'ignore'],
    }).trim()
    if (iso) return new Date(iso)
  } catch {}
  try {
    return fs.statSync(path.join(process.cwd(), relPath)).mtime
  } catch {}
  return new Date()
}

export default function sitemap(): MetadataRoute.Sitemap {
  const base = 'https://mintbrooks.com'
  const locales = routing.locales

  // Lifestyle pages — translated for every locale
  const lifestylePages: { path: string; src: string }[] = [
    { path: '',             src: 'src/app/[locale]/page.tsx' },
    { path: '/home-decor',  src: 'src/app/[locale]/home-decor/page.tsx' },
    { path: '/wellness',    src: 'src/app/[locale]/wellness/page.tsx' },
    { path: '/beauty',      src: 'src/app/[locale]/beauty/page.tsx' },
    { path: '/kitchen',     src: 'src/app/[locale]/kitchen/page.tsx' },
    { path: '/articles',    src: 'src/app/[locale]/articles/page.tsx' },
    { path: '/about',       src: 'src/app/[locale]/about/page.tsx' },
    { path: '/reading-list',src: 'src/app/[locale]/reading-list/page.tsx' },
    { path: '/search',      src: 'src/app/[locale]/page.tsx' },
    { path: '/privacy',     src: 'src/app/[locale]/privacy/page.tsx' },
    { path: '/terms',       src: 'src/app/[locale]/terms/page.tsx' },
  ]

  // Finance pages — English only, no locale prefix
  const financePages: { path: string; src: string }[] = [
    ['finance',                                      'page.tsx'],
    ['finance/calculator',                           'calculator/page.tsx'],
    ['finance/bad-credit-credit-card',               'bad-credit-credit-card/page.tsx'],
    ['finance/credit-card-500-credit-score',         'credit-card-500-credit-score/page.tsx'],
    ['finance/use-car-as-collateral',                'use-car-as-collateral/page.tsx'],
    ['finance/no-credit-history-credit-card',        'no-credit-history-credit-card/page.tsx'],
    ['finance/credit-card-no-deposit',               'credit-card-no-deposit/page.tsx'],
    ['finance/emergency-cash-between-paychecks',     'emergency-cash-between-paychecks/page.tsx'],
    ['finance/how-it-works',                         'how-it-works/page.tsx'],
    ['finance/car-title-loan-alternative',           'car-title-loan-alternative/page.tsx'],
    ['finance/car-equity-vs-secured-cards',          'car-equity-vs-secured-cards/page.tsx'],
    ['finance/how-to-build-credit-with-bad-credit',  'how-to-build-credit-with-bad-credit/page.tsx'],
    ['finance/how-to-get-credit-card-bad-credit-no-deposit', 'how-to-get-credit-card-bad-credit-no-deposit/page.tsx'],
    ['finance/yendo-states-guide',                   'yendo-states-guide/page.tsx'],
    ['finance/yendo-credit-card-review',             'yendo-credit-card-review/page.tsx'],
    ['finance/auto-equity-loan',                     'auto-equity-loan/page.tsx'],
    ['finance/credit-builder-loan',                  'credit-builder-loan/page.tsx'],
    ['finance/secured-credit-card-bad-credit',       'secured-credit-card-bad-credit/page.tsx'],
    ['finance/qualify',                              'qualify/page.tsx'],
    ['finance/how-to-rebuild-credit',                'how-to-rebuild-credit/page.tsx'],
    ['finance/first-credit-card-bad-credit',         'first-credit-card-bad-credit/page.tsx'],
    ['finance/credit-card-to-rebuild-credit',        'credit-card-to-rebuild-credit/page.tsx'],
    ['finance/faq',                                  'faq/page.tsx'],
    ['finance/yendo-review',                         'yendo-review/page.tsx'],
    ['finance/car-equity-credit-card-reviews',       'car-equity-credit-card-reviews/page.tsx'],
    ['finance/does-applying-for-credit-card-hurt-credit', 'does-applying-for-credit-card-hurt-credit/page.tsx'],
    ['finance/no-credit-check-credit-card',          'no-credit-check-credit-card/page.tsx'],
    ['finance/build-credit-with-your-car',           'build-credit-with-your-car/page.tsx'],
    ['finance/debt-consolidation-check',             'debt-consolidation-check/page.tsx'],
    ['finance/personal-loans-up-to-50k',             'personal-loans-up-to-50k/page.tsx'],
    ['finance/car-equity-loan-requirements',         'car-equity-loan-requirements/page.tsx'],
    ['finance/what-credit-score-do-you-need-for-a-credit-card', 'what-credit-score-do-you-need-for-a-credit-card/page.tsx'],
    ['finance/links',                                'links/page.tsx'],
  ].map(([p, rel]) => ({ path: `/${p}`, src: `src/app/finance/${rel}` }))

  // Articles — share lastmod of the source data file
  const articlesSrc = 'src/lib/lifestyle/articles.ts'
  const articlesMtime = gitMtime(articlesSrc)
  const articleSlugs = ARTICLES.map((a) => `/articles/${a.slug}`)

  // Use the module-level constants enumerated at build time
  const editorialEntries = EDITORIAL_FILES
  const affiliateEntries = AFFILIATE_FILES

  const entries: MetadataRoute.Sitemap = []

  for (const locale of locales) {
    const prefix = locale === 'en' ? '' : `/${locale}`
    for (const { path: p, src } of lifestylePages) {
      // Skip /articles for default locale: /public/articles/ static dir
      // shadows the dynamic /[locale]/articles route on Cloudflare Pages,
      // so the no-prefix URL returns 404. Locale-prefixed URLs are unaffected.
      if (locale === 'en' && (p === '/articles')) continue
      const url = `${base}${prefix}${p || '/'}`.replace(/\/$/, '') || base
      entries.push({ url, lastModified: gitMtime(src) })
    }
    for (const slug of articleSlugs) {
      if (locale === 'en') continue
      entries.push({ url: `${base}${prefix}${slug}`, lastModified: articlesMtime })
    }
  }

  for (const { path: p, src } of financePages) {
    entries.push({ url: `${base}${p}`, lastModified: gitMtime(src) })
  }

  for (const { slug, mtime } of editorialEntries) {
    // No .html — Next.js 308-redirects .html → no-extension; canonical matches
    entries.push({ url: `${base}/articles/editorial/${slug}`, lastModified: mtime })
  }

  for (const { slug, mtime } of affiliateEntries) {
    entries.push({ url: `${base}/articles/affiliate/${slug}/`, lastModified: mtime })
  }

  return entries
}
