import { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "How Top Listing Agents Use AI to Write 10x Better Descriptions in 5 Minutes",
  description:
    "Step-by-step workflow for using AI to write compelling listing descriptions: gather property data, build the right prompt, generate, edit. Includes a real prompt template for Claude and ChatGPT, plus tools with MLS integration.",
  openGraph: {
    title: "How Top Listing Agents Use AI to Write 10x Better Descriptions in 5 Minutes",
    description:
      "The exact AI workflow top listing agents use: property data collection, prompt structure, AI output, and editing. Includes prompt templates and tool recommendations.",
    type: "article",
  },
};

export default function ListingDescriptionAIWorkflowPage() {
  return (
    <>
      {/* Hero */}
      <section className="border-b border-white/10 bg-gradient-to-b from-[#111] to-[#0a0a0a] py-12 md:py-20">
        <div className="mx-auto max-w-3xl px-4">
          <div className="mb-4 flex flex-wrap items-center gap-2 text-sm text-white/50">
            <Link href="/" className="hover:text-white transition-colors">Home</Link>
            <span>/</span>
            <span>Guides</span>
            <span>/</span>
            <span className="text-white/70">Listing Description AI Workflow</span>
          </div>

          <div className="mb-4 inline-block rounded-full bg-[#059669]/10 px-3 py-1 text-xs font-medium text-[#059669]">
            Updated March 2026
          </div>

          <h1 className="text-3xl font-bold text-white md:text-4xl lg:text-5xl leading-tight">
            How Top Listing Agents Write 10x Better Descriptions in 5 Minutes Using AI
          </h1>

          <p className="mt-5 text-lg text-white/70 leading-relaxed">
            The average listing description takes 45–60 minutes to write well. Most agents
            spend that time staring at a blank page, recycling phrases from last week&apos;s
            listing, or writing copy that reads like it was generated by a 1999 MLS form.
            The top producers I know have cracked a different workflow — one where AI does
            the heavy lifting and they&apos;re editing and approving, not generating from scratch.
            Here&apos;s that workflow, step by step, with real prompt templates you can use today.
          </p>

          <div className="mt-6 flex flex-wrap gap-3 text-sm">
            <span className="flex items-center gap-1.5 rounded-full bg-white/5 px-3 py-1.5 text-white/60">
              <svg className="h-3.5 w-3.5 text-[#059669]" fill="currentColor" viewBox="0 0 20 20">
                <path fillRule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm1-12a1 1 0 10-2 0v4a1 1 0 00.293.707l2.828 2.829a1 1 0 101.415-1.415L11 9.586V6z" clipRule="evenodd" />
              </svg>
              ~10 min read
            </span>
            <span className="flex items-center gap-1.5 rounded-full bg-white/5 px-3 py-1.5 text-white/60">
              <svg className="h-3.5 w-3.5 text-green-400" fill="currentColor" viewBox="0 0 20 20">
                <path fillRule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clipRule="evenodd" />
              </svg>
              Includes real prompt template
            </span>
            <span className="flex items-center gap-1.5 rounded-full bg-white/5 px-3 py-1.5 text-white/60">
              <svg className="h-3.5 w-3.5 text-green-400" fill="currentColor" viewBox="0 0 20 20">
                <path fillRule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clipRule="evenodd" />
              </svg>
              MLS integration tools covered
            </span>
          </div>
        </div>
      </section>

      <div className="mx-auto max-w-3xl px-4 py-12">

        {/* Why this matters */}
        <div className="mb-12 rounded-2xl border border-[#059669]/20 bg-[#059669]/5 p-6">
          <p className="text-sm font-semibold uppercase tracking-wide text-[#059669] mb-3">
            Why Listing Copy Actually Matters
          </p>
          <p className="text-white/80 leading-relaxed mb-3">
            Zillow&apos;s research has found that listings with high-quality, descriptive copy
            receive up to 61% more views than sparse or generic descriptions. More views mean
            more showings. More showings mean better offers and faster closes. A great listing
            description isn&apos;t just marketing — it&apos;s a negotiating asset.
          </p>
          <p className="text-white/60 text-sm">
            The agents consistently getting top-dollar offers aren&apos;t spending 3x longer
            on copy. They&apos;re using AI to draft, and their expertise to refine.
          </p>
        </div>

        {/* Step 1 */}
        <section className="mb-14">
          <div className="mb-2 flex items-center gap-3">
            <div className="flex h-8 w-8 items-center justify-center rounded-full bg-[#059669]/20 text-sm font-bold text-[#059669]">
              1
            </div>
            <div className="mb-2 inline-block rounded-full bg-white/5 px-3 py-1 text-xs font-medium text-white/50">
              Step 1
            </div>
          </div>
          <h2 className="text-2xl font-bold text-white md:text-3xl mb-4">
            Gather the Raw Property Data (Before You Open Any AI Tool)
          </h2>

          <p className="text-white/70 leading-relaxed mb-6">
            The single biggest mistake agents make with AI listing copy is opening ChatGPT
            or Claude first. AI is a transformer, not a researcher. If you put generic inputs
            in, you get generic outputs out. The quality of your listing description is
            directly proportional to the quality of the data you feed into the prompt.
            Spend 5 minutes gathering before you start generating.
          </p>

          <div className="rounded-2xl border border-white/10 bg-[#111] p-6 mb-6">
            <p className="text-sm font-semibold text-[#059669] mb-4">Pre-prompt data checklist:</p>
            <div className="grid gap-3 sm:grid-cols-2">
              {[
                { cat: "Basics", items: ["Beds/baths/sqft", "Year built", "Lot size", "Garage details", "HOA or none"] },
                { cat: "Standout features", items: ["Kitchen upgrades (specify materials)", "Primary suite details", "Outdoor space specifics", "Views if any", "Storage/bonus rooms"] },
                { cat: "Recent updates", items: ["Year of last roof/HVAC/windows", "Any recent remodel", "New appliances", "Smart home features"] },
                { cat: "Neighborhood context", items: ["School district", "Walkability highlights", "Commute/transit", "Nearby amenities", "Neighborhood character"] },
              ].map((group) => (
                <div key={group.cat} className="rounded-lg bg-[#0a0a0a] p-3">
                  <p className="text-xs font-semibold text-[#059669] mb-2">{group.cat}</p>
                  <ul className="space-y-1">
                    {group.items.map((item) => (
                      <li key={item} className="flex items-center gap-2 text-xs text-white/60">
                        <span className="h-1 w-1 rounded-full bg-white/30 flex-shrink-0" />
                        {item}
                      </li>
                    ))}
                  </ul>
                </div>
              ))}
            </div>
          </div>

          <p className="text-white/60 text-sm">
            A good pre-prompt data sheet takes 4–6 minutes to fill in from your listing notes,
            the seller&apos;s disclosure, and a quick walkthrough of your photos. This is the
            time investment that makes everything else take 2 minutes.
          </p>
        </section>

        {/* Step 2 */}
        <section className="mb-14">
          <div className="mb-2 flex items-center gap-3">
            <div className="flex h-8 w-8 items-center justify-center rounded-full bg-[#059669]/20 text-sm font-bold text-[#059669]">
              2
            </div>
            <div className="mb-2 inline-block rounded-full bg-white/5 px-3 py-1 text-xs font-medium text-white/50">
              Step 2
            </div>
          </div>
          <h2 className="text-2xl font-bold text-white md:text-3xl mb-4">
            The Prompt Structure That Works
          </h2>

          <p className="text-white/70 leading-relaxed mb-6">
            Not all prompts are equal. A one-line request — &quot;write a listing description for
            a 4-bed house&quot; — will produce mediocre output every time. The prompt structure
            that consistently produces MLS-ready drafts has four components: role, property
            data, tone/format constraints, and the ask.
          </p>

          <div className="rounded-2xl border border-[#059669]/20 bg-[#0a0a0a] p-6 mb-6">
            <p className="text-sm font-semibold text-[#059669] mb-4">The Listing Description Prompt Template:</p>
            <div className="font-mono text-sm text-white/70 leading-relaxed space-y-3">
              <p className="text-white/50">— ROLE —</p>
              <p>You are an experienced real estate listing agent writing MLS copy for a property in [CITY, STATE]. Your writing style is warm, specific, and aspirational — you evoke lifestyle without being generic.</p>

              <p className="mt-4 text-white/50">— PROPERTY DATA —</p>
              <p>[Paste your completed data checklist here. Include every detail; the AI will select what matters most.]</p>

              <p className="mt-4 text-white/50">— TARGET BUYER —</p>
              <p>[e.g., "Young families prioritizing top-rated schools and backyard space" OR "Downsizing empty-nesters seeking walkability and low-maintenance living"]</p>

              <p className="mt-4 text-white/50">— FORMAT CONSTRAINTS —</p>
              <p>Write two versions:</p>
              <p>1. MLS short description: 150–200 words. No headline. Opens with the strongest selling point, not the address or "Welcome to..."</p>
              <p>2. Marketing long description: 300–350 words. Include a compelling opening line. Use short paragraphs. No bullet points. End with a call to action to schedule a showing.</p>

              <p className="mt-4 text-white/50">— AVOID —</p>
              <p>Do not use: "stunning," "gorgeous," "must-see," "cozy," "charming," "perfect for entertaining" as standalone claims without specifics. Make every adjective earn its place.</p>
            </div>
          </div>

          <div className="rounded-lg bg-amber-500/10 border border-amber-500/20 p-4">
            <p className="text-sm text-amber-400">
              <span className="font-semibold">Pro tip:</span> Save this prompt as a template in your AI tool of choice.
              Claude lets you create Projects with saved instructions; ChatGPT has Custom Instructions.
              That way you only paste the property data each time — the structure stays constant.
            </p>
          </div>
        </section>

        {/* Step 3 */}
        <section className="mb-14">
          <div className="mb-2 flex items-center gap-3">
            <div className="flex h-8 w-8 items-center justify-center rounded-full bg-[#059669]/20 text-sm font-bold text-[#059669]">
              3
            </div>
            <div className="mb-2 inline-block rounded-full bg-white/5 px-3 py-1 text-xs font-medium text-white/50">
              Step 3
            </div>
          </div>
          <h2 className="text-2xl font-bold text-white md:text-3xl mb-4">
            Running the Prompt: Tool Recommendations
          </h2>

          <p className="text-white/70 leading-relaxed mb-6">
            You can use this prompt in any AI tool, but the output quality and workflow
            efficiency vary. Here&apos;s how the main options compare specifically for listing copy:
          </p>

          <div className="space-y-5 mb-6">
            {[
              {
                name: "Claude (Anthropic)",
                tier: "Best overall output quality",
                price: "$20–$25/mo (Pro / Teams)",
                url: "https://claude.ai",
                description: "Claude consistently produces the most human-sounding, specific copy from this prompt structure. It follows format constraints reliably and avoids the generic phrasing that makes AI copy detectable. The Projects feature lets you save your prompt template and just paste property data for each new listing — a genuine time-saver if you do volume.",
                mlsIntegration: "No direct MLS integration — copy-paste workflow",
                bestFor: "Agents who write 5+ listings/month and want the best raw output quality",
              },
              {
                name: "ChatGPT (OpenAI)",
                tier: "Strong alternative",
                price: "$20/mo (Plus) or $25/user/mo (Teams)",
                url: "https://chat.openai.com",
                description: "GPT-4o produces excellent listing copy and is many agents' first choice simply because they already have a subscription. The Custom Instructions feature serves a similar purpose to Claude Projects. Output quality is comparable to Claude; the choice often comes down to personal preference after testing both with your specific property types.",
                mlsIntegration: "No direct MLS integration",
                bestFor: "Agents already subscribed to ChatGPT who don't want another subscription",
              },
              {
                name: "Lofty (formerly Chime)",
                tier: "Best MLS integration",
                price: "From $449/mo",
                url: "https://www.lofty.com",
                description: "Lofty has AI listing description generation built directly into its CRM and listing management workflow. You fill in property details within the platform and it generates copy without switching to a separate AI tool. The output quality is below Claude/ChatGPT, but for agents who prioritize workflow integration over copy quality, having everything in one place is a real advantage.",
                mlsIntegration: "Yes — native MLS data pull in supported markets",
                bestFor: "Teams running Lofty as their primary CRM who want AI copy without extra tools",
              },
              {
                name: "Canva Magic Write (for marketing)",
                tier: "Good for social/print versions",
                price: "Included with Canva Pro ($15/mo)",
                url: "https://www.canva.com",
                description: "Not an MLS description tool, but Canva Magic Write is useful for creating social media caption versions, flyer copy, and email subject lines from your MLS description. It's a fast way to spin one good description into 5 format-specific marketing pieces. Use after Claude/ChatGPT, not instead of.",
                mlsIntegration: "No",
                bestFor: "Agents who manage their own social/email marketing and want copy variety",
              },
            ].map((tool) => (
              <div key={tool.name} className="rounded-2xl border border-white/10 bg-[#111] p-6">
                <div className="flex items-start justify-between mb-3">
                  <div>
                    <div className="flex items-center gap-2 mb-1">
                      <h3 className="text-lg font-bold text-white">{tool.name}</h3>
                      <span className="rounded-full bg-[#059669]/20 px-2 py-0.5 text-xs font-medium text-[#059669]">
                        {tool.tier}
                      </span>
                    </div>
                    <p className="text-sm text-white/40">{tool.price}</p>
                  </div>
                </div>
                <p className="text-sm text-white/70 leading-relaxed mb-3">{tool.description}</p>
                <div className="mb-4 grid gap-2 rounded-lg bg-[#0a0a0a] p-3 text-xs sm:grid-cols-2">
                  <div>
                    <span className="text-white/40">MLS integration: </span>
                    <span className={tool.mlsIntegration.startsWith("Yes") ? "text-[#059669]" : "text-white/60"}>
                      {tool.mlsIntegration}
                    </span>
                  </div>
                  <div>
                    <span className="text-white/40">Best for: </span>
                    <span className="text-white/60">{tool.bestFor}</span>
                  </div>
                </div>
                <a
                  href={tool.url}
                  target="_blank"
                  rel="noopener noreferrer nofollow"
                  className="inline-block rounded-lg bg-[#059669] px-4 py-2 text-sm font-medium text-white hover:opacity-90 transition-opacity"
                >
                  Try {tool.name} →
                </a>
              </div>
            ))}
          </div>
        </section>

        {/* Step 4 */}
        <section className="mb-14">
          <div className="mb-2 flex items-center gap-3">
            <div className="flex h-8 w-8 items-center justify-center rounded-full bg-[#059669]/20 text-sm font-bold text-[#059669]">
              4
            </div>
            <div className="mb-2 inline-block rounded-full bg-white/5 px-3 py-1 text-xs font-medium text-white/50">
              Step 4
            </div>
          </div>
          <h2 className="text-2xl font-bold text-white md:text-3xl mb-4">
            The Edit: What to Fix Before It Goes Live
          </h2>

          <p className="text-white/70 leading-relaxed mb-6">
            Even a great AI draft needs a 3-minute edit pass. The AI doesn&apos;t know your
            market the way you do, it doesn&apos;t know your seller&apos;s personal attachment to
            that breakfast nook, and it can&apos;t check its own outputs for fair housing compliance.
            Here&apos;s the fast edit checklist I run on every AI-drafted listing:
          </p>

          <div className="space-y-3">
            {[
              {
                check: "Fair housing compliance review",
                detail: "Scan for any language that references neighborhood demographics, school district in ways that could imply protected class preferences, or family-suitability language. AI occasionally slips these in. Always catches-and-removes before submitting.",
              },
              {
                check: "Verify all specifics",
                detail: "If the AI says 'hardwood floors throughout,' confirm that's accurate. If it says 'mountain views,' make sure it's not just saying that because you mentioned hills in the data. AI occasionally embellishes. Your E&O insurance doesn't.",
              },
              {
                check: "Add your market-specific selling points",
                detail: "The AI doesn't know that your listing is 3 blocks from the best-rated elementary school in the county, or that the neighborhood has the highest walkability score in the city. Add those specifics in your own words.",
              },
              {
                check: "Punch up the opening line",
                detail: "AI opening lines are often good but safe. Read it aloud. If it doesn't pull you in, rewrite the first sentence in your own voice. That first line is doing heavy lifting.",
              },
              {
                check: "Check character/word count for MLS requirements",
                detail: "Different MLS systems have different character limits. The AI doesn't know your MLS rules; you do. Trim to fit before submitting.",
              },
            ].map((item, i) => (
              <div key={i} className="flex gap-4 rounded-xl border border-white/10 bg-[#111] p-4">
                <div className="flex h-6 w-6 flex-shrink-0 items-center justify-center rounded bg-[#059669]/20 text-xs font-bold text-[#059669]">
                  {i + 1}
                </div>
                <div>
                  <p className="font-semibold text-white text-sm">{item.check}</p>
                  <p className="mt-1 text-sm text-white/60 leading-relaxed">{item.detail}</p>
                </div>
              </div>
            ))}
          </div>
        </section>

        {/* Time math */}
        <section className="mb-12">
          <h2 className="text-2xl font-bold text-white mb-4">The Time Math</h2>
          <div className="overflow-x-auto rounded-xl border border-white/10">
            <table className="w-full text-sm">
              <thead>
                <tr className="border-b border-white/10 bg-[#111]">
                  <th className="px-4 py-3 text-left font-semibold text-white">Step</th>
                  <th className="px-4 py-3 text-left font-semibold text-white">Old way</th>
                  <th className="px-4 py-3 text-left font-semibold text-[#059669]">AI workflow</th>
                </tr>
              </thead>
              <tbody>
                {[
                  { step: "Research & data gathering", old: "15–20 min (scattered across notes/MLS)", ai: "5 min (structured checklist)" },
                  { step: "First draft", old: "25–35 min (writing from scratch)", ai: "2 min (AI generation)" },
                  { step: "Edit & compliance check", old: "10 min", ai: "3–5 min" },
                  { step: "Format for MLS + marketing", old: "15 min (rewrite for different formats)", ai: "3 min (AI generates variants)" },
                  { step: "Total per listing", old: "65–80 min", ai: "13–15 min" },
                ].map((row, i) => (
                  <tr key={i} className={`border-b border-white/5 ${i === 4 ? "bg-[#059669]/5 font-semibold" : ""}`}>
                    <td className="px-4 py-3 text-white">{row.step}</td>
                    <td className="px-4 py-3 text-white/50">{row.old}</td>
                    <td className="px-4 py-3 text-[#059669] font-medium">{row.ai}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
          <p className="mt-3 text-sm text-white/50">
            At 20 listings/month, that&apos;s 18–22 hours returned to prospecting, client calls, or
            actually leaving the office before dark.
          </p>
        </section>

        {/* Related */}
        <section className="mb-10 border-t border-white/10 pt-10">
          <h2 className="text-xl font-bold text-white mb-4">Related Guides &amp; Comparisons</h2>
          <div className="grid gap-4 md:grid-cols-2">
            <Link
              href="/compare/lofty-vs-follow-up-boss"
              className="group rounded-xl border border-white/10 bg-[#111] p-4 transition-all hover:border-[#059669]/30"
            >
              <p className="font-medium text-white group-hover:text-[#059669] transition-colors">
                Lofty vs. Follow Up Boss: CRM Comparison
              </p>
              <p className="mt-1 text-xs text-white/50">Which CRM has the best AI features for agents?</p>
            </Link>
            <Link
              href="/compare/best-ai-for-real-estate-lead-generation"
              className="group rounded-xl border border-white/10 bg-[#111] p-4 transition-all hover:border-[#059669]/30"
            >
              <p className="font-medium text-white group-hover:text-[#059669] transition-colors">
                Best AI for Real Estate Lead Generation
              </p>
              <p className="mt-1 text-xs text-white/50">Beyond listings: AI tools for finding and converting leads</p>
            </Link>
          </div>
        </section>

        {/* Disclosure */}
        <div className="rounded-xl border border-white/10 bg-[#111] p-4 text-xs text-white/40">
          <span className="font-semibold text-white/60">Affiliate Disclosure:</span>{" "}
          Links marked with an arrow (→) are affiliate links. We earn a commission if you
          sign up through these links at no cost to you. Our editorial rankings are
          independent of affiliate relationships.
        </div>
      </div>
    </>
  );
}
